import cv2
import numpy as np
import matplotlib.pyplot as plt
image = cv2.imread('virat kohli.jpg', cv2.IMREAD_GRAYSCALE)
if image is None:
    print("Error: Could not read the image.")
    exit()
equalized_image = cv2.equalizeHist(image)
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(image, cmap='gray')
plt.axis('off')
plt.subplot(1,2,2)
plt.title("Equalized Image")
plt.imshow(equalized_image, cmap='gray')
plt.axis('off')
plt.show()
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.title("Original Histogram")
plt.hist(image.ravel(), 256, [0,256])
plt.subplot(1,2,2)
plt.title("Equalized Histogram")
plt.hist(equalized_image.ravel(), 256, [0,256])
plt.show()